### ISSUE TITLE
Error en enlace

### ISSUE THREAD

**Issue by diegpied** [MicrosoftDocs/bot-docs.es-es#1]
In the document there is a link to https://docs.botframework.com/en-us/channel-inspector/channels/Skype/ and it's broken.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: f145183c-0c96-defc-a1d9-7f3662085292
* Version Independent ID: 880d8f18-5014-dc3e-8a46-0ba457ba680a
* Content: [Vista previa de las características del bot con Channel Inspector - Bot Service](https://docs.microsoft.com/es-es/azure/bot-service/bot-service-channel-inspector?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-inspector.md](https://github.com/MicrosoftDocs/bot-docs.es-es/blob/live/articles/bot-service-channel-inspector.md)
* Product: **bot-framework**
* GitHub Login: @RobStand
* Microsoft Alias: **kamrani**

**Comment by CeciAc** [comment]
Hello, @diegpied 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

**I cannot repro this issue, the link works on my side.**
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @diegpied 
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @diegpied
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
