### ISSUE TITLE
Error al provar el chat en web (python bot)

### ISSUE THREAD

**Issue by DannyCeb** [MicrosoftDocs/bot-docs.es-es#4]
Mi bot funciona perfectamente en el emulador pero al seguir los pasos de la documentación me encuentro con los siguientes problemas:

-No se puede habilitar el entorno virtual de python ($ source ./bin/activate) (Esto ya dentro de la carpeta wwwroot)

-El intentar correr el app.py  (Añadí el path del site packages manualmente dentro del código) me sale el error: 'OSError: [Errno 99] error while attemping to bind on address ('::1',3978,0,0): cannot assign requested address'

La documentación literalmente dice que al terminar de seguir los pasos el bot ya funciona pero la realidad no es así.

¿Me podrían ayudar a solucionar mi problema?
Gracias.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 096d934c-2856-e868-efeb-6622e2a5eafb
* Version Independent ID: 8bf74926-6a35-5753-0a1a-6663ba5965b2
* Content: [Implementación del bot: Bot Service - Bot Service](https://docs.microsoft.com/es-es/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=csharp#feedback)
* Content Source: [articles/bot-builder-deploy-az-cli.md](https://github.com/MicrosoftDocs/bot-docs.es-es/blob/live/articles/bot-builder-deploy-az-cli.md)
* Service: **bot-service**
* GitHub Login: @ivorb
* Microsoft Alias: **kamrani**

**Comment by srvbpigh** [comment]
Hello, @DannyCeb
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hola, @DannyCeb:  

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original.  

Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí: https://github.com/MicrosoftDocs/bot-docs/issues/1629.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  
Equipo internacional de Microsoft Docs
